// <auto-generated />
namespace Inventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fecha_en_ingresos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fecha_en_ingresos));
        
        string IMigrationMetadata.Id
        {
            get { return "201605041424162_fecha_en_ingresos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
