// <auto-generated />
namespace Inventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bodegas_sectores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bodegas_sectores));
        
        string IMigrationMetadata.Id
        {
            get { return "201605042135117_bodegas_sectores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
