// <auto-generated />
namespace Inventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class foreingkeybodega : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreingkeybodega));
        
        string IMigrationMetadata.Id
        {
            get { return "201605161328585_foreing key bodega"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
